; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3_kit35

[env:esp32s3_kit35]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino

; Serial Monitor options
monitor_speed = 115200
monitor_filters = 
    default
    time

; Upload options
upload_speed = 921600
board_build.partitions = default_16MB.csv

; Build options
build_flags = 
    -DFIRMWARE_VERSION=\"v1.0.0\"
    -DFIRMWARE_RELEASE_DATE=\"07/09/2026\"
    -DOTA_MANIFEST_URL=\"https://iot.tanhp.com/esp32s3kit35/version.json\"
    -DENABLE_SERIAL_LOG
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DUSE_NIMBLE
    -I include

lib_deps = 
    https://github.com/moononournation/Arduino_GFX.git#v1.4.9
    h2zero/NimBLE-Arduino@^1.4.3
