// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button4;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

